import { MongoClient } from 'mongodb';
import fs from 'fs';
import path from 'path';
import dotenv from 'dotenv';

dotenv.config();

const uri = process.env.MONGODB_URI;

// Sellers pool to distribute products realistically across cities in India
const SELLERS = [
  { id: "seller-delhi-1", name: "Aura Premium Electronics", pincode: "110001", city: "New Delhi", state: "Delhi" },
  { id: "seller-bengaluru-1", name: "Silicon Hub Digital", pincode: "560001", city: "Bengaluru", state: "Karnataka" },
  { id: "seller-mumbai-1", name: "Fort Commercial Retailers", pincode: "400001", city: "Mumbai", state: "Maharashtra" },
  { id: "seller-chennai-1", name: "Marina Trade & Mart", pincode: "600001", city: "Chennai", state: "Tamil Nadu" },
  { id: "seller-kolkata-1", name: "Howrah Grand Emporium", pincode: "700016", city: "Kolkata", state: "West Bengal" },
  { id: "seller-hyderabad-1", name: "Charminar Tech & Lifestyle", pincode: "500001", city: "Hyderabad", state: "Telangana" }
];

export const REAL_PRODUCTS: any[] = [
  // =========================================================================
  // 1. MOBILES (6-10 Products across subcategories)
  // =========================================================================
  {
    id: "apple-iphone-16-pro-max",
    _id: "apple-iphone-16-pro-max",
    name: "Apple iPhone 16 Pro Max (Natural Titanium, 256GB)",
    brand: "Apple",
    description: "Features a Grade 5 titanium design with microblasted finish. Super Retina XDR display with ProMotion 120Hz. Powered by the A18 Pro chip.",
    price: 144900,
    originalPrice: 159900,
    image: [
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=800&auto=format&fit=crop&q=80"
    ],
    category: "Mobiles",
    subcategory: "Smartphones",
    inventory: 24,
    rating: 4.9,
    reviewsCount: 1842,
    featured: true,
    sellerId: SELLERS[0].id, sellerName: SELLERS[0].name, sellerPincode: SELLERS[0].pincode, sellerCity: SELLERS[0].city, sellerState: SELLERS[0].state,
    availabilityRange: "india",
    tags: ["Aura Verified", "Free Delivery", "Express"],
    keyFeatures: ["A18 Pro Chip with 6-core GPU", "48MP Fusion Camera with 5x Telephoto", "Camera Control button"],
    specs: { "Display": "6.9-inch Super Retina XDR", "Storage": "256GB", "Processor": "A18 Pro" },
    createdAt: new Date().toISOString()
  },
  {
    id: "samsung-galaxy-s24-ultra-5g",
    _id: "samsung-galaxy-s24-ultra-5g",
    name: "Samsung Galaxy S24 Ultra 5G (Titanium Gray, 512GB)",
    brand: "Samsung",
    description: "Unleash Galaxy AI with Circle to Search, Live Translate, and Note Assist. Equipped with built-in S Pen and 200MP Quad Telephoto Camera.",
    price: 129999,
    originalPrice: 139999,
    image: ["https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&auto=format&fit=crop&q=80"],
    category: "Mobiles",
    subcategory: "Smartphones",
    inventory: 18,
    rating: 4.8,
    reviewsCount: 1250,
    featured: true,
    sellerId: SELLERS[1].id, sellerName: SELLERS[1].name, sellerPincode: SELLERS[1].pincode, sellerCity: SELLERS[1].city, sellerState: SELLERS[1].state,
    availabilityRange: "india",
    tags: ["Galaxy AI", "Free Delivery"],
    keyFeatures: ["Built-in S Pen", "200MP Main sensor", "Titanium Frame"],
    specs: { "RAM/Storage": "12GB / 512GB", "Battery": "5000 mAh" },
    createdAt: new Date().toISOString()
  },
  {
    id: "nokia-105-4g-feature-phone",
    _id: "nokia-105-4g-feature-phone",
    name: "Nokia 105 4G Feature Phone with UPI Payments (Black)",
    brand: "Nokia",
    description: "Durable classic feature phone with HD voice calling, long-lasting battery, built-in UPI payment support, and wireless FM radio.",
    price: 1299,
    originalPrice: 1799,
    image: ["https://images.unsplash.com/photo-1580910051074-3eb694886505?w=800&auto=format&fit=crop&q=80"],
    category: "Mobiles",
    subcategory: "Feature Phones",
    inventory: 50,
    rating: 4.4,
    reviewsCount: 3200,
    featured: false,
    sellerId: SELLERS[2].id, sellerName: SELLERS[2].name, sellerPincode: SELLERS[2].pincode, sellerCity: SELLERS[2].city, sellerState: SELLERS[2].state,
    availabilityRange: "india",
    tags: ["UPI Built-in", "Long Battery"],
    keyFeatures: ["4G VoLTE Calling", "Inbuilt UPI Pay app", "Wireless FM Radio & Torch"],
    specs: { "Battery": "1450 mAh", "SIM": "Dual SIM 4G" },
    createdAt: new Date().toISOString()
  },
  {
    id: "spigen-tough-armor-case-iphone-16",
    _id: "spigen-tough-armor-case-iphone-16",
    name: "Spigen Tough Armor MagFit Case for iPhone 16 Pro",
    brand: "Spigen",
    description: "Extreme dual-layer protection with Air Cushion Technology and built-in kickstand. MagSafe compatible with strong magnet ring.",
    price: 2499,
    originalPrice: 3499,
    image: ["https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=800&auto=format&fit=crop&q=80"],
    category: "Mobiles",
    subcategory: "Cases & Covers",
    inventory: 100,
    rating: 4.8,
    reviewsCount: 520,
    featured: false,
    sellerId: SELLERS[0].id, sellerName: SELLERS[0].name, sellerPincode: SELLERS[0].pincode, sellerCity: SELLERS[0].city, sellerState: SELLERS[0].state,
    availabilityRange: "india",
    tags: ["MagSafe Compatible", "Shockproof"],
    keyFeatures: ["Dual-layer shock absorption", "Reinforced kickstand"],
    specs: { "Material": "Polycarbonate & TPU", "Compatibility": "iPhone 16 Pro" },
    createdAt: new Date().toISOString()
  },
  {
    id: "anker-maggo-power-bank-10000mah",
    _id: "anker-maggo-power-bank-10000mah",
    name: "Anker MagGo 10,000mAh Magnetic Wireless Power Bank (15W Qi2)",
    brand: "Anker",
    description: "Certified 15W Qi2 wireless charging with smart color display showing exact battery percentage and charging time.",
    price: 6999,
    originalPrice: 8999,
    image: ["https://images.unsplash.com/photo-1609592424009-5a82196621fb?w=800&auto=format&fit=crop&q=80"],
    category: "Mobiles",
    subcategory: "Power Banks",
    inventory: 45,
    rating: 4.7,
    reviewsCount: 890,
    featured: false,
    sellerId: SELLERS[1].id, sellerName: SELLERS[1].name, sellerPincode: SELLERS[1].pincode, sellerCity: SELLERS[1].city, sellerState: SELLERS[1].state,
    availabilityRange: "india",
    tags: ["Fast Charging", "Qi2 Certified"],
    keyFeatures: ["15W Qi2 Wireless Charging", "Smart LED status display", "Foldable kickstand"],
    specs: { "Capacity": "10000 mAh", "Output": "USB-C 27W Max / Wireless 15W" },
    createdAt: new Date().toISOString()
  },
  {
    id: "apple-watch-ultra-2-gps-cellular",
    _id: "apple-watch-ultra-2-gps-cellular",
    name: "Apple Watch Ultra 2 GPS + Cellular (Titanium, Ocean Band)",
    brand: "Apple",
    description: "The ultimate sports and adventure watch. Brightest 3000-nit Always-On Retina display, S9 SiP chip, precision dual-frequency GPS.",
    price: 89900,
    originalPrice: 89900,
    image: ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80"],
    category: "Mobiles",
    subcategory: "Smart Watches",
    inventory: 15,
    rating: 4.9,
    reviewsCount: 430,
    featured: true,
    sellerId: SELLERS[0].id, sellerName: SELLERS[0].name, sellerPincode: SELLERS[0].pincode, sellerCity: SELLERS[0].city, sellerState: SELLERS[0].state,
    availabilityRange: "india",
    tags: ["Titanium Case", "Water Resistant 100m"],
    keyFeatures: ["3000 nits Peak Brightness", "Up to 36 hours battery life", "Customizable Action Button"],
    specs: { "Case Size": "49mm Titanium", "Connectivity": "Cellular + GPS" },
    createdAt: new Date().toISOString()
  },

  // =========================================================================
  // 2. ELECTRONICS (6-10 Products across subcategories)
  // =========================================================================
  {
    id: "apple-macbook-air-m3-15-inch",
    _id: "apple-macbook-air-m3-15-inch",
    name: "Apple MacBook Air M3 (15-inch, 16GB RAM, 512GB SSD - Midnight)",
    brand: "Apple",
    description: "Incredibly thin laptop with Apple M3 chip. Liquid Retina display, 1080p FaceTime HD camera, and up to 18 hours battery life.",
    price: 139900,
    originalPrice: 154900,
    image: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=800&auto=format&fit=crop&q=80"
    ],
    category: "Electronics",
    subcategory: "Laptops",
    inventory: 15,
    rating: 4.9,
    reviewsCount: 890,
    featured: true,
    sellerId: SELLERS[1].id, sellerName: SELLERS[1].name, sellerPincode: SELLERS[1].pincode, sellerCity: SELLERS[1].city, sellerState: SELLERS[1].state,
    availabilityRange: "india",
    tags: ["M3 Chip", "Free Shipping"],
    keyFeatures: ["8-core CPU and 10-core GPU", "Fanless silent design", "MagSafe 3 charging"],
    specs: { "Display": "15.3-inch Liquid Retina", "RAM": "16GB Unified", "Storage": "512GB SSD" },
    createdAt: new Date().toISOString()
  },
  {
    id: "sony-wh-1000xm5-wireless-headphones",
    _id: "sony-wh-1000xm5-wireless-headphones",
    name: "Sony WH-1000XM5 Wireless Noise Canceling Headphones (Black)",
    brand: "Sony",
    description: "Industry-leading noise cancellation with two processors and 8 microphones. Crystal clear hands-free calling with 4 beamforming mics.",
    price: 29990,
    originalPrice: 34990,
    image: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80"],
    category: "Electronics",
    subcategory: "Headphones",
    inventory: 40,
    rating: 4.8,
    reviewsCount: 3410,
    featured: true,
    sellerId: SELLERS[2].id, sellerName: SELLERS[2].name, sellerPincode: SELLERS[2].pincode, sellerCity: SELLERS[2].city, sellerState: SELLERS[2].state,
    availabilityRange: "india",
    tags: ["Best NC", "Hi-Res Audio"],
    keyFeatures: ["Auto NC Optimizer", "30-hour battery life", "Touch sensor controls"],
    specs: { "Driver": "30mm", "Battery": "30 Hours" },
    createdAt: new Date().toISOString()
  },
  {
    id: "sony-playstation-5-slim-console",
    _id: "sony-playstation-5-slim-console",
    name: "Sony PlayStation 5 Slim Digital Edition Console",
    brand: "Sony",
    description: "Experience lightning-fast loading with an ultra-high speed SSD, deeper immersion with support for haptic feedback, adaptive triggers and 3D Audio.",
    price: 44990,
    originalPrice: 49990,
    image: ["https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=800&auto=format&fit=crop&q=80"],
    category: "Electronics",
    subcategory: "Gaming Consoles",
    inventory: 20,
    rating: 4.9,
    reviewsCount: 2150,
    featured: true,
    sellerId: SELLERS[1].id, sellerName: SELLERS[1].name, sellerPincode: SELLERS[1].pincode, sellerCity: SELLERS[1].city, sellerState: SELLERS[1].state,
    availabilityRange: "india",
    tags: ["PS5 Slim", "Next-Gen Gaming"],
    keyFeatures: ["1TB NVMe SSD", "4K 120Hz Ray Tracing", "DualSense Controller"],
    specs: { "Storage": "1TB SSD", "Resolution": "Up to 4K 120 FPS" },
    createdAt: new Date().toISOString()
  },
  {
    id: "canon-eos-r6-mark-ii-camera",
    _id: "canon-eos-r6-mark-ii-camera",
    name: "Canon EOS R6 Mark II Mirrorless Camera (Body Only)",
    brand: "Canon",
    description: "24.2 MP Full-Frame CMOS Sensor with Dual Pixel CMOS AF II. High-speed continuous shooting up to 40 fps with electronic shutter.",
    price: 215995,
    originalPrice: 239995,
    image: ["https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format&fit=crop&q=80"],
    category: "Electronics",
    subcategory: "Cameras",
    inventory: 8,
    rating: 4.9,
    reviewsCount: 310,
    featured: false,
    sellerId: SELLERS[2].id, sellerName: SELLERS[2].name, sellerPincode: SELLERS[2].pincode, sellerCity: SELLERS[2].city, sellerState: SELLERS[2].state,
    availabilityRange: "india",
    tags: ["Pro Photography", "4K 60p Video"],
    keyFeatures: ["24.2MP Full-Frame sensor", "In-Body Image Stabilizer", "4K 60p video"],
    specs: { "Sensor": "24.2MP CMOS", "ISO": "100-102400" },
    createdAt: new Date().toISOString()
  },
  {
    id: "samsung-odyssey-g7-28-inch-4k-monitor",
    _id: "samsung-odyssey-g7-28-inch-4k-monitor",
    name: "Samsung Odyssey G7 28-inch 4K UHD 144Hz Gaming Monitor",
    brand: "Samsung",
    description: "UHD resolution with IPS panel, 1ms response time, 144Hz refresh rate, G-Sync compatibility and HDR400 for ultra-fluid gaming visuals.",
    price: 46990,
    originalPrice: 59990,
    image: ["https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80"],
    category: "Electronics",
    subcategory: "Monitors",
    inventory: 12,
    rating: 4.7,
    reviewsCount: 650,
    featured: false,
    sellerId: SELLERS[1].id, sellerName: SELLERS[1].name, sellerPincode: SELLERS[1].pincode, sellerCity: SELLERS[1].city, sellerState: SELLERS[1].state,
    availabilityRange: "india",
    tags: ["4K 144Hz", "G-Sync Compatible"],
    keyFeatures: ["1ms Response Time", "IPS 178° viewing angle", "CoreSync RGB Lighting"],
    specs: { "Resolution": "3840 x 2160 4K", "Refresh Rate": "144Hz" },
    createdAt: new Date().toISOString()
  },
  {
    id: "ipad-air-m2-11-inch-128gb",
    _id: "ipad-air-m2-11-inch-128gb",
    name: "Apple iPad Air M2 (11-inch, Wi-Fi, 128GB - Space Grey)",
    brand: "Apple",
    description: "Supercharged by the Apple M2 chip. Liquid Retina display, landscape front camera, Wi-Fi 6E, support for Apple Pencil Pro.",
    price: 59900,
    originalPrice: 64900,
    image: ["https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&auto=format&fit=crop&q=80"],
    category: "Electronics",
    subcategory: "Tablets",
    inventory: 22,
    rating: 4.8,
    reviewsCount: 1120,
    featured: false,
    sellerId: SELLERS[0].id, sellerName: SELLERS[0].name, sellerPincode: SELLERS[0].pincode, sellerCity: SELLERS[0].city, sellerState: SELLERS[0].state,
    availabilityRange: "india",
    tags: ["M2 Chip", "Pencil Pro Ready"],
    keyFeatures: ["Apple M2 Chip", "12MP Ultra Wide Landscape Front Camera", "Touch ID in top button"],
    specs: { "Screen": "11-inch Liquid Retina", "Storage": "128GB" },
    createdAt: new Date().toISOString()
  },

  // =========================================================================
  // 3. TV & APPLIANCES (6-10 Products)
  // =========================================================================
  {
    id: "lg-55-inch-4k-oled-evo-c3-tv",
    _id: "lg-55-inch-4k-oled-evo-c3-tv",
    name: "LG 55-inch 4K Smart OLED evo C3 TV (OLED55C3PSA)",
    brand: "LG",
    description: "Self-lit OLED pixels with α9 AI Processor 4K Gen6. Dolby Vision & Atmos, 120Hz refresh rate with VRR & G-Sync support for ultimate gaming and movies.",
    price: 119990,
    originalPrice: 169990,
    image: ["https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&auto=format&fit=crop&q=80"],
    category: "TV & Appliances",
    subcategory: "Smart TVs",
    inventory: 10,
    rating: 4.9,
    reviewsCount: 940,
    featured: true,
    sellerId: SELLERS[0].id, sellerName: SELLERS[0].name, sellerPincode: SELLERS[0].pincode, sellerCity: SELLERS[0].city, sellerState: SELLERS[0].state,
    availabilityRange: "india",
    tags: ["OLED evo", "120Hz Gaming"],
    keyFeatures: ["Self-lit OLED pixels", "α9 AI Processor 4K Gen6", "4x HDMI 2.1 ports"],
    specs: { "Display": "55-inch OLED 4K", "Audio": "40W Dolby Atmos" },
    createdAt: new Date().toISOString()
  },
  {
    id: "samsung-653l-side-by-side-refrigerator",
    _id: "samsung-653l-side-by-side-refrigerator",
    name: "Samsung 653L Convertible 5-in-1 Side-by-Side Refrigerator",
    brand: "Samsung",
    description: "Convertible 5-in-1 mode with Twin Cooling Plus technology, digital inverter compressor with 20-year warranty, and Wi-Fi SmartThings control.",
    price: 79990,
    originalPrice: 112000,
    image: ["https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&auto=format&fit=crop&q=80"],
    category: "TV & Appliances",
    subcategory: "Refrigerators",
    inventory: 8,
    rating: 4.8,
    reviewsCount: 510,
    featured: true,
    sellerId: SELLERS[2].id, sellerName: SELLERS[2].name, sellerPincode: SELLERS[2].pincode, sellerCity: SELLERS[2].city, sellerState: SELLERS[2].state,
    availabilityRange: "india",
    tags: ["20-Yr Warranty", "Convertible 5in1"],
    keyFeatures: ["Twin Cooling Plus", "SmartThings App control", "Auto ice & water dispenser"],
    specs: { "Capacity": "653 Litres", "Energy Rating": "3 Star" },
    createdAt: new Date().toISOString()
  },
  {
    id: "daikin-1-5-ton-5-star-inverter-ac",
    _id: "daikin-1-5-ton-5-star-inverter-ac",
    name: "Daikin 1.5 Ton 5 Star Inverter Split AC (Copper, PM 2.5 Filter)",
    brand: "Daikin",
    description: "Dew Clean technology, 3D Airflow, 100% copper condenser coil, power chill operation, and 10-year compressor warranty.",
    price: 44990,
    originalPrice: 58400,
    image: ["https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&auto=format&fit=crop&q=80"],
    category: "TV & Appliances",
    subcategory: "Air Conditioners",
    inventory: 16,
    rating: 4.7,
    reviewsCount: 1820,
    featured: false,
    sellerId: SELLERS[0].id, sellerName: SELLERS[0].name, sellerPincode: SELLERS[0].pincode, sellerCity: SELLERS[0].city, sellerState: SELLERS[0].state,
    availabilityRange: "india",
    tags: ["5 Star Energy", "PM 2.5 Filter"],
    keyFeatures: ["Dew Clean self cleaning", "Triple Display", "Cooling at 52°C extreme heat"],
    specs: { "Capacity": "1.5 Ton", "Energy Rating": "5 Star" },
    createdAt: new Date().toISOString()
  },
  {
    id: "ifb-8kg-front-load-washing-machine",
    _id: "ifb-8kg-front-load-washing-machine",
    name: "IFB 8 kg 5 Star AI Front Load Washing Machine (Steam Wash)",
    brand: "IFB",
    description: "Powered by AI neural network that detects fabric type and load weight to optimize wash duration and water usage. Built-in heater with 99.9% germ elimination.",
    price: 34990,
    originalPrice: 42990,
    image: ["https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=800&auto=format&fit=crop&q=80"],
    category: "TV & Appliances",
    subcategory: "Washing Machines",
    inventory: 14,
    rating: 4.8,
    reviewsCount: 1430,
    featured: false,
    sellerId: SELLERS[1].id, sellerName: SELLERS[1].name, sellerPincode: SELLERS[1].pincode, sellerCity: SELLERS[1].city, sellerState: SELLERS[1].state,
    availabilityRange: "india",
    tags: ["AI Powered", "4-Yr Warranty"],
    keyFeatures: ["Aqua Energie hard water treatment", "Cradle wash for delicate silk", "Steam Refresh cycle"],
    specs: { "Capacity": "8 kg", "RPM": "1400 RPM" },
    createdAt: new Date().toISOString()
  },
  {
    id: "dyson-v12-detect-slim-vacuum-cleaner",
    _id: "dyson-v12-detect-slim-vacuum-cleaner",
    name: "Dyson V12 Detect Slim Cordless Vacuum Cleaner",
    brand: "Dyson",
    description: "Laser reveals invisible dust on hard floors. Piezo sensor automatically adapts suction power based on dust volume. LCD screen displays real-time proof of deep clean.",
    price: 49900,
    originalPrice: 55900,
    image: ["https://images.unsplash.com/photo-1558317374-067fb5f30001?w=800&auto=format&fit=crop&q=80"],
    category: "TV & Appliances",
    subcategory: "Vacuum Cleaners",
    inventory: 12,
    rating: 4.9,
    reviewsCount: 720,
    featured: true,
    sellerId: SELLERS[0].id, sellerName: SELLERS[0].name, sellerPincode: SELLERS[0].pincode, sellerCity: SELLERS[0].city, sellerState: SELLERS[0].state,
    availabilityRange: "india",
    tags: ["Dyson Laser Tech", "HEPA Filtration"],
    keyFeatures: ["Illuminated cleaner head", "Up to 60 min fade-free suction", "Hair screw tool for pet hair"],
    specs: { "Weight": "2.2 kg", "Suction Power": "150 AW" },
    createdAt: new Date().toISOString()
  },
  {
    id: "kent-grand-plus-ro-water-purifier",
    _id: "kent-grand-plus-ro-water-purifier",
    name: "KENT Grand Plus 9-Litre Mineral RO + UV + UF Water Purifier",
    brand: "KENT",
    description: "Patented Mineral RO technology retains essential natural minerals in purified water using a TDS controller. Fully automatic operation.",
    price: 16490,
    originalPrice: 20000,
    image: ["https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&auto=format&fit=crop&q=80"],
    category: "TV & Appliances",
    subcategory: "Water Purifiers",
    inventory: 25,
    rating: 4.6,
    reviewsCount: 2890,
    featured: false,
    sellerId: SELLERS[3].id, sellerName: SELLERS[3].name, sellerPincode: SELLERS[3].pincode, sellerCity: SELLERS[3].city, sellerState: SELLERS[3].state,
    availabilityRange: "india",
    tags: ["Mineral RO", "Zero Water Wastage"],
    keyFeatures: ["9L Storage Tank", "20 L/hr purification capacity", "UV LED light in storage tank"],
    specs: { "Capacity": "9 Litres", "Purification": "RO + UV + UF + TDS Control" },
    createdAt: new Date().toISOString()
  },

  // =========================================================================
  // 4. FASHION (6-10 Products)
  // =========================================================================
  {
    id: "levis-501-original-fit-jeans",
    _id: "levis-501-original-fit-jeans",
    name: "Levi's 501 Original Fit Straight Leg Jeans (Dark Wash Denim)",
    brand: "Levi's",
    description: "The classic blue jean since 1873. Crafted with heavyweight 100% cotton denim, signature button fly, and iconic red tab.",
    price: 4599,
    originalPrice: 5999,
    image: ["https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&auto=format&fit=crop&q=80"],
    category: "Fashion",
    subcategory: "Men Jeans",
    inventory: 60,
    rating: 4.6,
    reviewsCount: 3200,
    featured: false,
    sellerId: SELLERS[4].id, sellerName: SELLERS[4].name, sellerPincode: SELLERS[4].pincode, sellerCity: SELLERS[4].city, sellerState: SELLERS[4].state,
    availabilityRange: "india",
    tags: ["100% Cotton", "Classic Denim"],
    keyFeatures: ["Original straight fit", "Signature button fly", "5-pocket styling"],
    specs: { "Fit": "Straight Fit", "Fabric": "100% Cotton" },
    createdAt: new Date().toISOString()
  },
  {
    id: "manyavar-royal-silk-sherwani-set",
    _id: "manyavar-royal-silk-sherwani-set",
    name: "Manyavar Royal Zari Embellished Silk Sherwani Set",
    brand: "Manyavar",
    description: "Exquisite cream and gold silk sherwani featuring detailed thread zari embroidery, mandarin collar, and matching churidar pants.",
    price: 18999,
    originalPrice: 24999,
    image: ["https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80"],
    category: "Fashion",
    subcategory: "Ethnic Wear",
    inventory: 15,
    rating: 4.9,
    reviewsCount: 420,
    featured: true,
    sellerId: SELLERS[0].id, sellerName: SELLERS[0].name, sellerPincode: SELLERS[0].pincode, sellerCity: SELLERS[0].city, sellerState: SELLERS[0].state,
    availabilityRange: "india",
    tags: ["Wedding Collection", "Handcrafted Zari"],
    keyFeatures: ["Art Silk Fabric with inner lining", "Comes with Churidar bottoms", "Dry clean only"],
    specs: { "Material": "Silk Blend", "Pattern": "Embroidered Zari" },
    createdAt: new Date().toISOString()
  },
  {
    id: "fabindia-pure-chanderi-silk-saree",
    _id: "fabindia-pure-chanderi-silk-saree",
    name: "Fabindia Handwoven Chanderi Silk Saree with Zari Border",
    brand: "Fabindia",
    description: "Handcrafted Chanderi silk saree with rich woven gold zari border and delicate floral motifs. Includes unstitched blouse piece.",
    price: 8990,
    originalPrice: 11500,
    image: ["https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80"],
    category: "Fashion",
    subcategory: "Sarees",
    inventory: 20,
    rating: 4.8,
    reviewsCount: 610,
    featured: true,
    sellerId: SELLERS[4].id, sellerName: SELLERS[4].name, sellerPincode: SELLERS[4].pincode, sellerCity: SELLERS[4].city, sellerState: SELLERS[4].state,
    availabilityRange: "india",
    tags: ["Handloom Silk", "Fabindia Certified"],
    keyFeatures: ["6.3 meters with blouse piece", "Authentic Chanderi silk weave"],
    specs: { "Fabric": "Pure Chanderi Silk", "Occasion": "Festive / Traditional" },
    createdAt: new Date().toISOString()
  },
  {
    id: "us-polo-assn-pique-cotton-polo-tshirt",
    _id: "us-polo-assn-pique-cotton-polo-tshirt",
    name: "U.S. Polo Assn. Men Solid Cotton Pique Polo T-Shirt",
    brand: "U.S. Polo Assn.",
    description: "Classic short-sleeve polo shirt crafted from 100% breathable cotton pique fabric featuring signature embroidered logo on chest.",
    price: 1499,
    originalPrice: 2299,
    image: ["https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=80"],
    category: "Fashion",
    subcategory: "Men T-Shirts",
    inventory: 80,
    rating: 4.5,
    reviewsCount: 4500,
    featured: false,
    sellerId: SELLERS[2].id, sellerName: SELLERS[2].name, sellerPincode: SELLERS[2].pincode, sellerCity: SELLERS[2].city, sellerState: SELLERS[2].state,
    availabilityRange: "india",
    tags: ["100% Cotton", "Polo Fit"],
    keyFeatures: ["Ribbed collar and sleeve cuffs", "Two-button placket"],
    specs: { "Fabric": "100% Cotton Pique", "Sleeve": "Short Sleeve" },
    createdAt: new Date().toISOString()
  },
  {
    id: "zara-tailored-double-breasted-blazer",
    _id: "zara-tailored-double-breasted-blazer",
    name: "Zara Men Structured Double-Breasted Formal Blazer",
    brand: "Zara",
    description: "Sharp slim-fit double breasted suit jacket with peak lapels, flap pockets, and back vents. Ideal for formal and evening events.",
    price: 7990,
    originalPrice: 9990,
    image: ["https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800&auto=format&fit=crop&q=80"],
    category: "Fashion",
    subcategory: "Blazers",
    inventory: 18,
    rating: 4.7,
    reviewsCount: 380,
    featured: false,
    sellerId: SELLERS[2].id, sellerName: SELLERS[2].name, sellerPincode: SELLERS[2].pincode, sellerCity: SELLERS[2].city, sellerState: SELLERS[2].state,
    availabilityRange: "india",
    tags: ["Slim Fit", "Formal Wear"],
    keyFeatures: ["Double-breasted button closure", "Viscose viscose viscose inner lining"],
    specs: { "Fit": "Slim Fit", "Lining": "100% Polyester" },
    createdAt: new Date().toISOString()
  },

  // =========================================================================
  // 5. FOOTWEAR (6-10 Products)
  // =========================================================================
  {
    id: "nike-air-jordan-1-retro-high-og",
    _id: "nike-air-jordan-1-retro-high-og",
    name: "Nike Air Jordan 1 Retro High OG Sneakers (Chicago Red)",
    brand: "Nike",
    description: "Iconic high-top silhouette crafted with premium full-grain leather, encapsulated Air cushioning, and original Chicago color-blocking.",
    price: 16995,
    originalPrice: 18995,
    image: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1552346154-21d32810aba3?w=800&auto=format&fit=crop&q=80"
    ],
    category: "Footwear",
    subcategory: "Sneakers",
    inventory: 28,
    rating: 4.9,
    reviewsCount: 1420,
    featured: true,
    sellerId: SELLERS[3].id, sellerName: SELLERS[3].name, sellerPincode: SELLERS[3].pincode, sellerCity: SELLERS[3].city, sellerState: SELLERS[3].state,
    availabilityRange: "india",
    tags: ["Authentic Sneaker", "Nike Air"],
    keyFeatures: ["Full-grain genuine leather", "Encapsulated Air sole unit"],
    specs: { "Type": "High-Top Sneaker", "Closure": "Lace-Up" },
    createdAt: new Date().toISOString()
  },
  {
    id: "adidas-ultraboost-light-running-shoes",
    _id: "adidas-ultraboost-light-running-shoes",
    name: "Adidas Ultraboost Light Running Shoes (Core Black)",
    brand: "Adidas",
    description: "Lightest Ultraboost ever made with 30% lighter Light BOOST material. Primeknit+ upper for supreme adaptive fit and Continental rubber outsole.",
    price: 13999,
    originalPrice: 18999,
    image: ["https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&auto=format&fit=crop&q=80"],
    category: "Footwear",
    subcategory: "Sports Shoes",
    inventory: 35,
    rating: 4.8,
    reviewsCount: 2100,
    featured: false,
    sellerId: SELLERS[1].id, sellerName: SELLERS[1].name, sellerPincode: SELLERS[1].pincode, sellerCity: SELLERS[1].city, sellerState: SELLERS[1].state,
    availabilityRange: "india",
    tags: ["Boost Cushioning", "Marathon Grade"],
    keyFeatures: ["Light BOOST midsole technology", "Continental™ Better Rubber outsole"],
    specs: { "Weight": "299 grams", "Midsole Drop": "10 mm" },
    createdAt: new Date().toISOString()
  },
  {
    id: "clarks-tilden-cap-oxford-formal-shoes",
    _id: "clarks-tilden-cap-oxford-formal-shoes",
    name: "Clarks Tilden Cap Leather Oxford Formal Shoes (Tan)",
    brand: "Clarks",
    description: "Classic cap-toe Oxford crafted from high-shine dark tan leather. Features Cushion Soft foam padding and flexible rubber sole for all-day comfort.",
    price: 6999,
    originalPrice: 8999,
    image: ["https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=800&auto=format&fit=crop&q=80"],
    category: "Footwear",
    subcategory: "Formal Shoes",
    inventory: 40,
    rating: 4.7,
    reviewsCount: 890,
    featured: false,
    sellerId: SELLERS[0].id, sellerName: SELLERS[0].name, sellerPincode: SELLERS[0].pincode, sellerCity: SELLERS[0].city, sellerState: SELLERS[0].state,
    availabilityRange: "india",
    tags: ["Real Leather", "OrthoLite Insole"],
    keyFeatures: ["Full grain leather upper", "Discreet elastic gore panels for quick slip-on"],
    specs: { "Upper": "Leather", "Sole": "TPR Rubber" },
    createdAt: new Date().toISOString()
  },
  {
    id: "woodland-leather-rugged-outdoor-boots",
    _id: "woodland-leather-rugged-outdoor-boots",
    name: "Woodland Men's Leather Rugged Outdoor Trekking Boots (Camel)",
    brand: "Woodland",
    description: "Heavy duty genuine nubuck leather high-ankle boots with deep cleated rubber sole. Designed for wilderness trekking and tough outdoor terrains.",
    price: 4995,
    originalPrice: 5995,
    image: ["https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=800&auto=format&fit=crop&q=80"],
    category: "Footwear",
    subcategory: "Boots",
    inventory: 50,
    rating: 4.6,
    reviewsCount: 5400,
    featured: false,
    sellerId: SELLERS[4].id, sellerName: SELLERS[4].name, sellerPincode: SELLERS[4].pincode, sellerCity: SELLERS[4].city, sellerState: SELLERS[4].state,
    availabilityRange: "india",
    tags: ["Heavy Duty", "Nubuck Leather"],
    keyFeatures: ["Rustproof brass eyelets", "Deep lugged anti-skid rubber tread"],
    specs: { "Material": "Nubuck Leather", "Sole": "Raw Rubber" },
    createdAt: new Date().toISOString()
  },

  // =========================================================================
  // 6. BEAUTY & PERSONAL CARE (6-10 Products)
  // =========================================================================
  {
    id: "dior-sauvage-eau-de-parfum-100ml",
    _id: "dior-sauvage-eau-de-parfum-100ml",
    name: "Dior Sauvage Eau de Parfum Spray (100ml)",
    brand: "Dior",
    description: "An intensely fresh interpretation of Sauvage, combining radiant Calabrian Bergamot with sensual Papua New Guinean Vanilla absolute.",
    price: 13500,
    originalPrice: 15000,
    image: ["https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&auto=format&fit=crop&q=80"],
    category: "Beauty & Personal Care",
    subcategory: "Perfumes",
    inventory: 40,
    rating: 4.9,
    reviewsCount: 2900,
    featured: true,
    sellerId: SELLERS[2].id, sellerName: SELLERS[2].name, sellerPincode: SELLERS[2].pincode, sellerCity: SELLERS[2].city, sellerState: SELLERS[2].state,
    availabilityRange: "india",
    tags: ["Luxury Fragrance", "Long Lasting"],
    keyFeatures: ["Notes: Bergamot, Sichuan Pepper, Vanilla", "Eau de Parfum concentration"],
    specs: { "Volume": "100ml", "Gender": "Men" },
    createdAt: new Date().toISOString()
  },
  {
    id: "estee-lauder-advanced-night-repair",
    _id: "estee-lauder-advanced-night-repair",
    name: "Estée Lauder Advanced Night Repair Synchronized Serum (50ml)",
    brand: "Estée Lauder",
    description: "Harnesses Chronolux Power Signal Technology to significantly reduce the look of multiple signs of aging caused by environmental assaults.",
    price: 9500,
    originalPrice: 10800,
    image: ["https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&auto=format&fit=crop&q=80"],
    category: "Beauty & Personal Care",
    subcategory: "Skincare",
    inventory: 25,
    rating: 4.8,
    reviewsCount: 1650,
    featured: false,
    sellerId: SELLERS[0].id, sellerName: SELLERS[0].name, sellerPincode: SELLERS[0].pincode, sellerCity: SELLERS[0].city, sellerState: SELLERS[0].state,
    availabilityRange: "india",
    tags: ["Anti-Aging", "Hyaluronic Acid"],
    keyFeatures: ["72-hour hydration boost", "Oil-free non-acnegenic formula"],
    specs: { "Volume": "50ml", "Skin Type": "All Skin Types" },
    createdAt: new Date().toISOString()
  },
  {
    id: "dyson-airwrap-multi-styler-complete-long",
    _id: "dyson-airwrap-multi-styler-complete-long",
    name: "Dyson Airwrap Multi-Styler Complete Long (Nickel/Copper)",
    brand: "Dyson",
    description: "Curl, shape, smooth and hide flyaways with no extreme heat. Utilizes Coanda airflow tech to wrap hair automatically.",
    price: 49900,
    originalPrice: 52900,
    image: ["https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&auto=format&fit=crop&q=80"],
    category: "Beauty & Personal Care",
    subcategory: "Hair Care",
    inventory: 15,
    rating: 4.9,
    reviewsCount: 1240,
    featured: true,
    sellerId: SELLERS[0].id, sellerName: SELLERS[0].name, sellerPincode: SELLERS[0].pincode, sellerCity: SELLERS[0].city, sellerState: SELLERS[0].state,
    availabilityRange: "india",
    tags: ["Coanda Airflow", "No Heat Damage"],
    keyFeatures: ["Includes 6 attachments & presentation case", "Intelligent heat control below 150°C"],
    specs: { "Power": "1300 Watts", "Cable Length": "2.68 m" },
    createdAt: new Date().toISOString()
  },
  {
    id: "philips-series-9000-beard-trimmer",
    _id: "philips-series-9000-beard-trimmer",
    name: "Philips Series 9000 Prestige Waterproof Beard Trimmer",
    brand: "Philips",
    description: "SteelPrecision blades with 30 length settings from 0.4mm to 10mm. Steel sensor adjusts power 125 times per second for dense beards.",
    price: 8495,
    originalPrice: 10995,
    image: ["https://images.unsplash.com/photo-1621607512214-68297480165e?w=800&auto=format&fit=crop&q=80"],
    category: "Beauty & Personal Care",
    subcategory: "Beard Care",
    inventory: 30,
    rating: 4.7,
    reviewsCount: 980,
    featured: false,
    sellerId: SELLERS[2].id, sellerName: SELLERS[2].name, sellerPincode: SELLERS[2].pincode, sellerCity: SELLERS[2].city, sellerState: SELLERS[2].state,
    availabilityRange: "india",
    tags: ["Self-Sharpening", "100% Waterproof"],
    keyFeatures: ["120 min lithium-ion cordless runtime", "Full metal body frame"],
    specs: { "Settings": "30 Lengths", "Battery": "120 Mins" },
    createdAt: new Date().toISOString()
  },

  // =========================================================================
  // 7. HOME & KITCHEN (6-10 Products)
  // =========================================================================
  {
    id: "nespresso-vertuo-next-coffee-machine",
    _id: "nespresso-vertuo-next-coffee-machine",
    name: "Nespresso Vertuo Next Espresso & Coffee Machine (Matte Black)",
    brand: "Nespresso",
    description: "Centrifusion technology reads the barcode on each capsule to brew barista-quality single-serve coffee and authentic espresso.",
    price: 18990,
    originalPrice: 22990,
    image: ["https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=800&auto=format&fit=crop&q=80"],
    category: "Home & Kitchen",
    subcategory: "Kitchen Tools",
    inventory: 22,
    rating: 4.8,
    reviewsCount: 760,
    featured: true,
    sellerId: SELLERS[0].id, sellerName: SELLERS[0].name, sellerPincode: SELLERS[0].pincode, sellerCity: SELLERS[0].city, sellerState: SELLERS[0].state,
    availabilityRange: "india",
    tags: ["Barista Grade", "Nespresso"],
    keyFeatures: ["5 Cup sizes: Espresso to Carafe", "Fast 25 sec heat up time"],
    specs: { "Water Tank": "1.1 Litres", "Power": "1500 Watts" },
    createdAt: new Date().toISOString()
  },
  {
    id: "le-creuset-enameled-cast-iron-dutch-oven",
    _id: "le-creuset-enameled-cast-iron-dutch-oven",
    name: "Le Creuset Enameled Cast Iron Signature Round Dutch Oven (5.5 Qt, Cerise)",
    brand: "Le Creuset",
    description: "Handcrafted legendary French cast iron oven. Superior heat distribution and retention for slow cooking, roasting, baking, and simmering.",
    price: 32900,
    originalPrice: 38000,
    image: ["https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=800&auto=format&fit=crop&q=80"],
    category: "Home & Kitchen",
    subcategory: "Cookware",
    inventory: 10,
    rating: 4.9,
    reviewsCount: 430,
    featured: true,
    sellerId: SELLERS[2].id, sellerName: SELLERS[2].name, sellerPincode: SELLERS[2].pincode, sellerCity: SELLERS[2].city, sellerState: SELLERS[2].state,
    availabilityRange: "india",
    tags: ["French Made", "Lifetime Warranty"],
    keyFeatures: ["Colorful vibrant enamel resists chipping", "Safe for all stovetops including induction & oven"],
    specs: { "Capacity": "5.5 Quarts / 5.2 Litres", "Material": "Enameled Cast Iron" },
    createdAt: new Date().toISOString()
  },
  {
    id: "philips-hue-white-color-ambiance-starter-kit",
    _id: "philips-hue-white-color-ambiance-starter-kit",
    name: "Philips Hue White & Color Ambiance Smart Bulb Starter Kit with Hue Bridge",
    brand: "Philips Hue",
    description: "Transform your home lighting with 16 million colors and tunable white spectrum. Sync with music, movies, and gaming via Alexa, Apple Home, Google.",
    price: 12999,
    originalPrice: 15999,
    image: ["https://images.unsplash.com/photo-1550985616-10810253b84d?w=800&auto=format&fit=crop&q=80"],
    category: "Home & Kitchen",
    subcategory: "Lighting",
    inventory: 35,
    rating: 4.7,
    reviewsCount: 1290,
    featured: false,
    sellerId: SELLERS[1].id, sellerName: SELLERS[1].name, sellerPincode: SELLERS[1].pincode, sellerCity: SELLERS[1].city, sellerState: SELLERS[1].state,
    availabilityRange: "india",
    tags: ["16M Colors", "Smart Home"],
    keyFeatures: ["Includes 3 Smart E27 Bulbs + Hue Bridge", "Voice control via Alexa & Google Assistant"],
    specs: { "Base": "E27", "Brightness": "806 Lumens per bulb" },
    createdAt: new Date().toISOString()
  },

  // =========================================================================
  // 8. FURNITURE (6-10 Products)
  // =========================================================================
  {
    id: "urban-ladder-ergonomic-executive-chair",
    _id: "urban-ladder-ergonomic-executive-chair",
    name: "Urban Ladder Motion Ergonomic Mesh Office Chair",
    brand: "Urban Ladder",
    description: "High-back office chair with adjustable lumbar support, 3D armrests, breathable Korean mesh backrest, and heavy-duty chrome wheelbase.",
    price: 14999,
    originalPrice: 19999,
    image: ["https://images.unsplash.com/photo-1580481072645-022f9a6d8310?w=800&auto=format&fit=crop&q=80"],
    category: "Furniture",
    subcategory: "Office Chairs",
    inventory: 14,
    rating: 4.7,
    reviewsCount: 610,
    featured: false,
    sellerId: SELLERS[1].id, sellerName: SELLERS[1].name, sellerPincode: SELLERS[1].pincode, sellerCity: SELLERS[1].city, sellerState: SELLERS[1].state,
    availabilityRange: "india",
    tags: ["3-Year Warranty", "Ergonomic"],
    keyFeatures: ["135° lockable synchro-tilt recline", "BIFMA Class-4 gas lift"],
    specs: { "Frame": "Nylon", "Max Load": "140 kg" },
    createdAt: new Date().toISOString()
  },
  {
    id: "godrej-interio-royal-3-seater-velvet-sofa",
    _id: "godrej-interio-royal-3-seater-velvet-sofa",
    name: "Godrej Interio Royal 3-Seater Premium Velvet Fabric Sofa (Navy Blue)",
    brand: "Godrej Interio",
    description: "Crafted with solid teak wood inner frame and high-resilience 32-density foam seating. Upholstered in stain-resistant plush velvet.",
    price: 28990,
    originalPrice: 38990,
    image: ["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&auto=format&fit=crop&q=80"],
    category: "Furniture",
    subcategory: "Sofas",
    inventory: 10,
    rating: 4.8,
    reviewsCount: 390,
    featured: true,
    sellerId: SELLERS[0].id, sellerName: SELLERS[0].name, sellerPincode: SELLERS[0].pincode, sellerCity: SELLERS[0].city, sellerState: SELLERS[0].state,
    availabilityRange: "india",
    tags: ["Solid Teak Wood", "Stain Resistant"],
    keyFeatures: ["32 density high resilience foam", "Reinforced solid wood legs"],
    specs: { "Dimensions": "195 x 85 x 88 cm", "Seating": "3 Seater" },
    createdAt: new Date().toISOString()
  },
  {
    id: "wakefit-orthopedic-memory-foam-king-mattress",
    _id: "wakefit-orthopedic-memory-foam-king-mattress",
    name: "Wakefit ShapeSense Orthopedic Memory Foam King Size Mattress (78x72x8 inch)",
    brand: "Wakefit",
    description: "Targeted 7-zone body support layer aligns spine naturally while reducing pressure points. Removable zipper breathable fabric cover.",
    price: 13490,
    originalPrice: 18990,
    image: ["https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&auto=format&fit=crop&q=80"],
    category: "Furniture",
    subcategory: "Mattresses",
    inventory: 40,
    rating: 4.8,
    reviewsCount: 14500,
    featured: false,
    sellerId: SELLERS[1].id, sellerName: SELLERS[1].name, sellerPincode: SELLERS[1].pincode, sellerCity: SELLERS[1].city, sellerState: SELLERS[1].state,
    availabilityRange: "india",
    tags: ["10-Year Warranty", "Orthopedic Approved"],
    keyFeatures: ["ShapeSense Memory Foam technology", "Motion separation zero transfer"],
    specs: { "Size": "King (78x72 Inches)", "Thickness": "8 Inches" },
    createdAt: new Date().toISOString()
  },

  // =========================================================================
  // 9. GROCERY (6-10 Products)
  // =========================================================================
  {
    id: "fortune-biryani-special-basmati-rice-5kg",
    _id: "fortune-biryani-special-basmati-rice-5kg",
    name: "Fortune Biryani Special Premium Aged Basmati Rice (5kg Bag)",
    brand: "Fortune",
    description: "Extra-long grain aromatic basmati rice aged for 2 years. Grains elongate to twice their length upon cooking without stickiness.",
    price: 849,
    originalPrice: 1100,
    image: ["https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800&auto=format&fit=crop&q=80"],
    category: "Grocery",
    subcategory: "Rice",
    inventory: 100,
    rating: 4.7,
    reviewsCount: 6800,
    featured: false,
    sellerId: SELLERS[4].id, sellerName: SELLERS[4].name, sellerPincode: SELLERS[4].pincode, sellerCity: SELLERS[4].city, sellerState: SELLERS[4].state,
    availabilityRange: "india",
    tags: ["Aged 2 Years", "Extra Long Grain"],
    keyFeatures: ["100% pure authentic basmati", "Perfect non-sticky fluffy texture"],
    specs: { "Quantity": "5 kg", "Type": "Basmati" },
    createdAt: new Date().toISOString()
  },
  {
    id: "ferrero-rocher-gourmet-chocolate-box-24-pcs",
    _id: "ferrero-rocher-gourmet-chocolate-box-24-pcs",
    name: "Ferrero Rocher Premium Hazelnut Chocolates Gift Box (24 Pieces)",
    brand: "Ferrero Rocher",
    description: "Whole crunchy hazelnut center surrounded by smooth creamy chocolate filling, encased in crisp wafer shell with milk chocolate and chopped hazelnut pieces.",
    price: 899,
    originalPrice: 1099,
    image: ["https://images.unsplash.com/photo-1548907040-4baa42d10919?w=800&auto=format&fit=crop&q=80"],
    category: "Grocery",
    subcategory: "Chocolates",
    inventory: 120,
    rating: 4.9,
    reviewsCount: 9200,
    featured: true,
    sellerId: SELLERS[0].id, sellerName: SELLERS[0].name, sellerPincode: SELLERS[0].pincode, sellerCity: SELLERS[0].city, sellerState: SELLERS[0].state,
    availabilityRange: "india",
    tags: ["Gold Foil Wrapped", "Imported Quality"],
    keyFeatures: ["Golden box presentation", "Premium Italian roasted hazelnuts"],
    specs: { "Weight": "300g (24 Pcs)", "Type": "Hazelnut Milk Chocolate" },
    createdAt: new Date().toISOString()
  },
  {
    id: "happilo-premium-afghan-cashews-almonds-walnuts-combo",
    _id: "happilo-premium-afghan-cashews-almonds-walnuts-combo",
    name: "Happilo 100% Natural Raw Jumbo Cashews, California Almonds & Chilean Walnuts (1kg)",
    brand: "Happilo",
    description: "Vacuum sealed fresh superfood pack containing handpicked crunchy jumbo cashews, almonds, and brain-healthy whole walnut kernels.",
    price: 1199,
    originalPrice: 1799,
    image: ["https://images.unsplash.com/photo-1509358211525-a8439d5b433e?w=800&auto=format&fit=crop&q=80"],
    category: "Grocery",
    subcategory: "Dry Fruits",
    inventory: 75,
    rating: 4.8,
    reviewsCount: 4100,
    featured: false,
    sellerId: SELLERS[2].id, sellerName: SELLERS[2].name, sellerPincode: SELLERS[2].pincode, sellerCity: SELLERS[2].city, sellerState: SELLERS[2].state,
    availabilityRange: "india",
    tags: ["Superfood Combo", "No Preservatives"],
    keyFeatures: ["Rich in Omega 3 & antioxidants", "Nitrogen flushed zipper pack"],
    specs: { "Weight": "1 kg (330g x 3)", "Diet": "Gluten Free & Vegan" },
    createdAt: new Date().toISOString()
  },

  // =========================================================================
  // 10. BABY CARE (6-10 Products)
  // =========================================================================
  {
    id: "pampers-premium-care-diaper-pants-l",
    _id: "pampers-premium-care-diaper-pants-l",
    name: "Pampers Premium Care Diaper Pants (Large Size 62 Count)",
    brand: "Pampers",
    description: "360-degree soft cottony stretch waist tape with aloe vera lotion layer for zero rash irritation and up to 12 hours dryness lock.",
    price: 1299,
    originalPrice: 1699,
    image: ["https://images.unsplash.com/photo-1519689680058-324335c77eba?w=800&auto=format&fit=crop&q=80"],
    category: "Baby Care",
    subcategory: "Diapers",
    inventory: 90,
    rating: 4.8,
    reviewsCount: 11200,
    featured: false,
    sellerId: SELLERS[0].id, sellerName: SELLERS[0].name, sellerPincode: SELLERS[0].pincode, sellerCity: SELLERS[0].city, sellerState: SELLERS[0].state,
    availabilityRange: "india",
    tags: ["Rash Free", "12 Hr Dryness"],
    keyFeatures: ["Wetness indicator line turning blue", "3 Air Channels for breathable airflow"],
    specs: { "Size": "Large (9-14 kg)", "Count": "62 Pants" },
    createdAt: new Date().toISOString()
  },
  {
    id: "chicco-seety-lightweight-baby-stroller",
    _id: "chicco-seety-lightweight-baby-stroller",
    name: "Chicco Seety Compact Lightweight Foldable Baby Stroller (Grey)",
    brand: "Chicco",
    description: "One-hand instant compact fold stroller with multi-recline padded seat, UV50+ expandable canopy, and shock absorber suspension wheels.",
    price: 11990,
    originalPrice: 15990,
    image: ["https://images.unsplash.com/photo-1591088398332-8a7791972843?w=800&auto=format&fit=crop&q=80"],
    category: "Baby Care",
    subcategory: "Strollers",
    inventory: 15,
    rating: 4.9,
    reviewsCount: 380,
    featured: true,
    sellerId: SELLERS[1].id, sellerName: SELLERS[1].name, sellerPincode: SELLERS[1].pincode, sellerCity: SELLERS[1].city, sellerState: SELLERS[1].state,
    availabilityRange: "india",
    tags: ["EN1888 Certified", "One Hand Fold"],
    keyFeatures: ["Suitable from 0 to 22 kg", "5-point safety harness with padded pads"],
    specs: { "Weight": "7.2 kg", "Age": "0 to 4 Years" },
    createdAt: new Date().toISOString()
  },

  // =========================================================================
  // 11. TOYS & GAMES (6-10 Products)
  // =========================================================================
  {
    id: "lego-star-wars-millennium-falcon",
    _id: "lego-star-wars-millennium-falcon",
    name: "LEGO Star Wars Millennium Falcon Ultimate Building Set",
    brand: "LEGO",
    description: "Build and display an iconic Star Wars starship. Features rotating top/bottom gun turrets, 2 spring-loaded shooters, lowering ramp.",
    price: 13999,
    originalPrice: 16999,
    image: ["https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=800&auto=format&fit=crop&q=80"],
    category: "Toys & Games",
    subcategory: "Building Blocks",
    inventory: 15,
    rating: 4.9,
    reviewsCount: 540,
    featured: true,
    sellerId: SELLERS[0].id, sellerName: SELLERS[0].name, sellerPincode: SELLERS[0].pincode, sellerCity: SELLERS[0].city, sellerState: SELLERS[0].state,
    availabilityRange: "india",
    tags: ["1351 Pieces", "Star Wars"],
    keyFeatures: ["Includes 7 minifigures", "Detailed internal cargo & cockpit"],
    specs: { "Pieces": "1351", "Age": "9+ Years" },
    createdAt: new Date().toISOString()
  },
  {
    id: "catan-board-game-5th-edition",
    _id: "catan-board-game-5th-edition",
    name: "CATAN Strategy Board Game (5th Edition Base Game)",
    brand: "CATAN",
    description: "The world famous resource management strategy game. Trade, build and settle the island of Catan with variable hexagonal tile layout.",
    price: 3499,
    originalPrice: 4299,
    image: ["https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800&auto=format&fit=crop&q=80"],
    category: "Toys & Games",
    subcategory: "Board Games",
    inventory: 40,
    rating: 4.8,
    reviewsCount: 2890,
    featured: false,
    sellerId: SELLERS[2].id, sellerName: SELLERS[2].name, sellerPincode: SELLERS[2].pincode, sellerCity: SELLERS[2].city, sellerState: SELLERS[2].state,
    availabilityRange: "india",
    tags: ["Award Winning", "3-4 Players"],
    keyFeatures: ["60 minute play time", "Infinite map variations"],
    specs: { "Players": "3 to 4 Players", "Age": "10+ Years" },
    createdAt: new Date().toISOString()
  },

  // =========================================================================
  // 12. SPORTS & FITNESS (6-10 Products)
  // =========================================================================
  {
    id: "bowflex-selecttech-552-adjustable-dumbbells",
    _id: "bowflex-selecttech-552-adjustable-dumbbells",
    name: "Bowflex SelectTech 552 Adjustable Dumbbells Pair (2kg - 24kg)",
    brand: "Bowflex",
    description: "Replaces 15 sets of weights. Adjusts from 2 to 24 kg in 1 kg increments with a simple turn of a dial.",
    price: 34990,
    originalPrice: 42990,
    image: ["https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&auto=format&fit=crop&q=80"],
    category: "Sports & Fitness",
    subcategory: "Dumbbells",
    inventory: 12,
    rating: 4.9,
    reviewsCount: 780,
    featured: true,
    sellerId: SELLERS[3].id, sellerName: SELLERS[3].name, sellerPincode: SELLERS[3].pincode, sellerCity: SELLERS[3].city, sellerState: SELLERS[3].state,
    availabilityRange: "india",
    tags: ["Home Gym", "Space Saver"],
    keyFeatures: ["Dial weight selection mechanism", "Durable quiet metal plate molding"],
    specs: { "Weight": "2 to 24 kg per hand", "Count": "Pair of 2" },
    createdAt: new Date().toISOString()
  },
  {
    id: "manduka-pro-yoga-mat-6mm",
    _id: "manduka-pro-yoga-mat-6mm",
    name: "Manduka PRO High Density Premium Yoga Mat (6mm, Black Sage)",
    brand: "Manduka",
    description: "Ultra-dense cushioning supports joint protection, unmatched grip stability, and closed-cell surface prevents moisture sweat absorption.",
    price: 9990,
    originalPrice: 12500,
    image: ["https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=800&auto=format&fit=crop&q=80"],
    category: "Sports & Fitness",
    subcategory: "Yoga Mats",
    inventory: 25,
    rating: 4.9,
    reviewsCount: 1650,
    featured: false,
    sellerId: SELLERS[1].id, sellerName: SELLERS[1].name, sellerPincode: SELLERS[1].pincode, sellerCity: SELLERS[1].city, sellerState: SELLERS[1].state,
    availabilityRange: "india",
    tags: ["Lifetime Guarantee", "Studio Grade"],
    keyFeatures: ["100% latex-free non toxic OEKO-TEX certified", "Proprietary dot pattern bottom grip"],
    specs: { "Thickness": "6 mm", "Length": "180 cm x 66 cm" },
    createdAt: new Date().toISOString()
  },

  // =========================================================================
  // 13. BOOKS & MEDIA (6-10 Products)
  // =========================================================================
  {
    id: "atomic-habits-james-clear-hardcover",
    _id: "atomic-habits-james-clear-hardcover",
    name: "Atomic Habits: An Easy & Proven Way to Build Good Habits (Hardcover)",
    brand: "Penguin Random House",
    description: "The #1 New York Times bestseller by James Clear. Learn actionable strategies for forming good habits, breaking bad ones, and mastering tiny behaviors.",
    price: 699,
    originalPrice: 999,
    image: ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80"],
    category: "Books & Media",
    subcategory: "Non-fiction",
    inventory: 150,
    rating: 4.9,
    reviewsCount: 15400,
    featured: false,
    sellerId: SELLERS[4].id, sellerName: SELLERS[4].name, sellerPincode: SELLERS[4].pincode, sellerCity: SELLERS[4].city, sellerState: SELLERS[4].state,
    availabilityRange: "india",
    tags: ["#1 Bestseller", "Hardcover"],
    keyFeatures: ["Practical framework for self growth", "Includes habit loop trackers"],
    specs: { "Format": "Hardcover", "Pages": "320 Pages" },
    createdAt: new Date().toISOString()
  },
  {
    id: "kindle-paperwhite-16gb-6-8-display",
    _id: "kindle-paperwhite-16gb-6-8-display",
    name: "Kindle Paperwhite (16 GB) – 6.8\" display and adjustable warm light",
    brand: "Amazon Kindle",
    description: "Purpose-built for reading with a flush-front design and 300 ppi glare-free display that reads like real paper, even in bright sunlight.",
    price: 13999,
    originalPrice: 15999,
    image: ["https://images.unsplash.com/photo-1592496001020-d31bd830651f?w=800&auto=format&fit=crop&q=80"],
    category: "Books & Media",
    subcategory: "E-books",
    inventory: 30,
    rating: 4.8,
    reviewsCount: 4200,
    featured: true,
    sellerId: SELLERS[0].id, sellerName: SELLERS[0].name, sellerPincode: SELLERS[0].pincode, sellerCity: SELLERS[0].city, sellerState: SELLERS[0].state,
    availabilityRange: "india",
    tags: ["Waterproof IPX8", "10 Wk Battery"],
    keyFeatures: ["USB-C charging", "Adjustable warm light spectrum"],
    specs: { "Screen": "6.8 Inches 300 ppi", "Storage": "16GB" },
    createdAt: new Date().toISOString()
  },

  // =========================================================================
  // 14. AUTOMOTIVE (6-10 Products)
  // =========================================================================
  {
    id: "royal-enfield-urban-trooper-helmet",
    _id: "royal-enfield-urban-trooper-helmet",
    name: "Royal Enfield Urban Trooper Full Face Helmet (Matte Black, L)",
    brand: "Royal Enfield",
    description: "ISI and DOT certified full-face motorcycle helmet. High-impact ABS shell with EPS density liner and anti-scratch UV resistant visor.",
    price: 4200,
    originalPrice: 4999,
    image: ["https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=800&auto=format&fit=crop&q=80"],
    category: "Automotive",
    subcategory: "Helmets",
    inventory: 30,
    rating: 4.8,
    reviewsCount: 620,
    featured: false,
    sellerId: SELLERS[3].id, sellerName: SELLERS[3].name, sellerPincode: SELLERS[3].pincode, sellerCity: SELLERS[3].city, sellerState: SELLERS[3].state,
    availabilityRange: "india",
    tags: ["DOT & ISI Certified", "UV Visor"],
    keyFeatures: ["Aerodynamic vents", "Removable washable inner liner"],
    specs: { "Size": "Large (59-60 cm)", "Certification": "ISI & DOT" },
    createdAt: new Date().toISOString()
  },
  {
    id: "70mai-pro-plus-a500s-dash-cam",
    _id: "70mai-pro-plus-a500s-dash-cam",
    name: "70mai Pro Plus+ A500S Dual Channel 2.7K Car Dash Camera with GPS",
    brand: "70mai",
    description: "2.7K QHD recording with Sony IMX335 sensor, built-in GPS, ADAS lane departure warnings, and night vision 3D DNR.",
    price: 9999,
    originalPrice: 12999,
    image: ["https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800&auto=format&fit=crop&q=80"],
    category: "Automotive",
    subcategory: "Car Accessories",
    inventory: 20,
    rating: 4.7,
    reviewsCount: 1450,
    featured: true,
    sellerId: SELLERS[1].id, sellerName: SELLERS[1].name, sellerPincode: SELLERS[1].pincode, sellerCity: SELLERS[1].city, sellerState: SELLERS[1].state,
    availabilityRange: "india",
    tags: ["2.7K QHD", "Built-in GPS & ADAS"],
    keyFeatures: ["App Wi-Fi viewing", "G-sensor emergency auto lock"],
    specs: { "Resolution": "2592 x 1944P QHD", "Sensor": "Sony IMX335" },
    createdAt: new Date().toISOString()
  },

  // =========================================================================
  // 15. JEWELLERY (6-10 Products)
  // =========================================================================
  {
    id: "tanishq-18k-yellow-gold-diamond-pendant-necklace",
    _id: "tanishq-18k-yellow-gold-diamond-pendant-necklace",
    name: "Tanishq 18K Yellow Gold & Solitaire Diamond Pendant Necklace",
    brand: "Tanishq",
    description: "Certified 18 Karat solid gold necklace with sparkling VVS-GH certified 0.25 carat brilliant solitaire diamond pendant.",
    price: 34990,
    originalPrice: 39990,
    image: ["https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&auto=format&fit=crop&q=80"],
    category: "Jewellery",
    subcategory: "Gold Jewellery",
    inventory: 10,
    rating: 4.9,
    reviewsCount: 310,
    featured: true,
    sellerId: SELLERS[0].id, sellerName: SELLERS[0].name, sellerPincode: SELLERS[0].pincode, sellerCity: SELLERS[0].city, sellerState: SELLERS[0].state,
    availabilityRange: "india",
    tags: ["BIS Hallmarked", "Certified Diamond"],
    keyFeatures: ["BIS 750 Hallmarked Gold", "Includes IGI Certificate of Authenticity"],
    specs: { "Gold Purity": "18K Yellow Gold", "Diamond Weight": "0.25 Carat" },
    createdAt: new Date().toISOString()
  },
  {
    id: "giva-925-sterling-silver-zircon-ring",
    _id: "giva-925-sterling-silver-zircon-ring",
    name: "GIVA 925 Sterling Silver Adjustable Solitaire Zircon Ring",
    brand: "GIVA",
    description: "Pure 925 silver ring featuring a sparkling AAA+ Grade Cubic Zirconia stone. Coated with anti-tarnish rhodium layer for long lasting shine.",
    price: 1899,
    originalPrice: 3299,
    image: ["https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&auto=format&fit=crop&q=80"],
    category: "Jewellery",
    subcategory: "Silver Jewellery",
    inventory: 60,
    rating: 4.8,
    reviewsCount: 5200,
    featured: false,
    sellerId: SELLERS[2].id, sellerName: SELLERS[2].name, sellerPincode: SELLERS[2].pincode, sellerCity: SELLERS[2].city, sellerState: SELLERS[2].state,
    availabilityRange: "india",
    tags: ["925 Silver Stamp", "Rhodium Plated"],
    keyFeatures: ["Adjustable ring size fits all fingers", "Includes GIVA certificate"],
    specs: { "Purity": "925 Sterling Silver", "Stone": "AAA+ Zirconia" },
    createdAt: new Date().toISOString()
  },

  // =========================================================================
  // 16. WATCHES (6-10 Products)
  // =========================================================================
  {
    id: "fossil-grant-chronograph-leather-watch",
    _id: "fossil-grant-chronograph-leather-watch",
    name: "Fossil Grant Chronograph Brown Leather Watch",
    brand: "Fossil",
    description: "Inspired by vintage clocks, Roman numeral markers, stainless steel case, and genuine rich brown leather strap.",
    price: 11995,
    originalPrice: 14995,
    image: ["https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&auto=format&fit=crop&q=80"],
    category: "Watches",
    subcategory: "Men's Watches",
    inventory: 30,
    rating: 4.7,
    reviewsCount: 880,
    featured: false,
    sellerId: SELLERS[0].id, sellerName: SELLERS[0].name, sellerPincode: SELLERS[0].pincode, sellerCity: SELLERS[0].city, sellerState: SELLERS[0].state,
    availabilityRange: "india",
    tags: ["Genuine Leather", "2-Year Warranty"],
    keyFeatures: ["44mm Stainless steel case", "5 ATM water resistance"],
    specs: { "Movement": "Quartz Chronograph", "Strap": "Genuine Leather" },
    createdAt: new Date().toISOString()
  },
  {
    id: "titan-raga-viva-rose-gold-women-watch",
    _id: "titan-raga-viva-rose-gold-women-watch",
    name: "Titan Raga Viva Rose Gold Dial Stainless Steel Bracelet Watch",
    brand: "Titan",
    description: "Elegantly sculpted rose gold analog watch with mother-of-pearl dial and Swarovski crystal markers.",
    price: 6495,
    originalPrice: 7995,
    image: ["https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800&auto=format&fit=crop&q=80"],
    category: "Watches",
    subcategory: "Women's Watches",
    inventory: 25,
    rating: 4.8,
    reviewsCount: 1340,
    featured: true,
    sellerId: SELLERS[4].id, sellerName: SELLERS[4].name, sellerPincode: SELLERS[4].pincode, sellerCity: SELLERS[4].city, sellerState: SELLERS[4].state,
    availabilityRange: "india",
    tags: ["Titan Warranty", "Swarovski Elements"],
    keyFeatures: ["Mother of Pearl dial texture", "3 ATM water resistance"],
    specs: { "Case": "Rose Gold Plated", "Strap": "Jewelry Clasp Bangle" },
    createdAt: new Date().toISOString()
  },

  // =========================================================================
  // 17. BAGS, WALLETS & LUGGAGE (6-10 Products)
  // =========================================================================
  {
    id: "samsonite-omni-pc-hard-side-spinner-suitcase",
    _id: "samsonite-omni-pc-hard-side-spinner-suitcase",
    name: "Samsonite Omni PC Hard-Side Expandable 28-inch Spinner Luggage",
    brand: "Samsonite",
    description: "Micro-diamond polycarbonate texture is extremely scratch-resistant. TSA side-mounted lock and multidirectional airflow spinner wheels.",
    price: 16990,
    originalPrice: 22000,
    image: ["https://images.unsplash.com/photo-1565026057447-b88e3f29042b?w=800&auto=format&fit=crop&q=80"],
    category: "Bags, Wallets & Luggage",
    subcategory: "Suitcases",
    inventory: 15,
    rating: 4.9,
    reviewsCount: 1890,
    featured: true,
    sellerId: SELLERS[2].id, sellerName: SELLERS[2].name, sellerPincode: SELLERS[2].pincode, sellerCity: SELLERS[2].city, sellerState: SELLERS[2].state,
    availabilityRange: "india",
    tags: ["10-Yr Warranty", "TSA Lock"],
    keyFeatures: ["100% Polycarbonate shell", "360-degree dual spinner wheels"],
    specs: { "Size": "28 Inches (Large Check-In)", "Weight": "4.6 kg" },
    createdAt: new Date().toISOString()
  },
  {
    id: "wildcraft-35l-laptop-backpack-black",
    _id: "wildcraft-35l-laptop-backpack-black",
    name: "Wildcraft 35L Water Resistant Laptop Backpack with Rain Cover",
    brand: "Wildcraft",
    description: "3 spacious compartments with dedicated 15.6-inch padded laptop sleeve, organizer pockets, and attached waterproof rain cover.",
    price: 1999,
    originalPrice: 3299,
    image: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80"],
    category: "Bags, Wallets & Luggage",
    subcategory: "Backpacks",
    inventory: 80,
    rating: 4.6,
    reviewsCount: 8900,
    featured: false,
    sellerId: SELLERS[1].id, sellerName: SELLERS[1].name, sellerPincode: SELLERS[1].pincode, sellerCity: SELLERS[1].city, sellerState: SELLERS[1].state,
    availabilityRange: "india",
    tags: ["Rain Cover Included", "Ergonomic Back"],
    keyFeatures: ["Hypagrip back padding", "Built-in key clip & bottle holder"],
    specs: { "Capacity": "35 Litres", "Laptop Size": "Up to 15.6 Inches" },
    createdAt: new Date().toISOString()
  },

  // =========================================================================
  // 18. PET SUPPLIES (6-10 Products)
  // =========================================================================
  {
    id: "royal-canin-maxi-adult-dry-dog-food-15kg",
    _id: "royal-canin-maxi-adult-dry-dog-food-15kg",
    name: "Royal Canin Maxi Adult Dry Dog Food (15kg Bag)",
    brand: "Royal Canin",
    description: "Specifically formulated for large breed dogs (26 to 44 kg). Supports bone & joint health, easy digestibility, and enriched with EPA-DHA.",
    price: 7890,
    originalPrice: 8900,
    image: ["https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=800&auto=format&fit=crop&q=80"],
    category: "Pet Supplies",
    subcategory: "Dog Food",
    inventory: 25,
    rating: 4.8,
    reviewsCount: 2300,
    featured: false,
    sellerId: SELLERS[0].id, sellerName: SELLERS[0].name, sellerPincode: SELLERS[0].pincode, sellerCity: SELLERS[0].city, sellerState: SELLERS[0].state,
    availabilityRange: "india",
    tags: ["Vet Recommended", "Large Breed"],
    keyFeatures: ["Omega 3 fatty acids for skin & coat", "High digestibility protein"],
    specs: { "Weight": "15 kg", "Life Stage": "Adult (15 months - 5 years)" },
    createdAt: new Date().toISOString()
  },

  // =========================================================================
  // 19. MUSICAL INSTRUMENTS (6-10 Products)
  // =========================================================================
  {
    id: "yamaha-f310-acoustic-guitar-natural",
    _id: "yamaha-f310-acoustic-guitar-natural",
    name: "Yamaha F310 Full Size Acoustic Guitar (Natural Gloss)",
    brand: "Yamaha",
    description: "The ultimate acoustic guitar for beginners and seasoned players. Features a spruce top, rosewood fingerboard, and resonant dreadnought body.",
    price: 10490,
    originalPrice: 12490,
    image: ["https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=800&auto=format&fit=crop&q=80"],
    category: "Musical Instruments",
    subcategory: "Guitar",
    inventory: 25,
    rating: 4.8,
    reviewsCount: 1920,
    featured: false,
    sellerId: SELLERS[2].id, sellerName: SELLERS[2].name, sellerPincode: SELLERS[2].pincode, sellerCity: SELLERS[2].city, sellerState: SELLERS[2].state,
    availabilityRange: "india",
    tags: ["Yamaha Original", "Spruce Top"],
    keyFeatures: ["Dreadnought body shape", "Locally sourced tonewood back & sides"],
    specs: { "Fingerboard": "Rosewood", "Strings": "6 Steel Strings" },
    createdAt: new Date().toISOString()
  },

  // =========================================================================
  // 20. OFFICE SUPPLIES (6-10 Products)
  // =========================================================================
  {
    id: "casio-fx-991ex-classwiz-scientific-calculator",
    _id: "casio-fx-991ex-classwiz-scientific-calculator",
    name: "Casio FX-991EX ClassWiz Advanced Scientific Calculator",
    brand: "Casio",
    description: "High-resolution Natural Textbook Display with 552 functions including spreadsheet, matrix calculations, and QR code visualizer.",
    price: 1595,
    originalPrice: 1895,
    image: ["https://images.unsplash.com/photo-1594980596870-8aa52a78d8cd?w=800&auto=format&fit=crop&q=80"],
    category: "Office Supplies",
    subcategory: "Calculators",
    inventory: 90,
    rating: 4.9,
    reviewsCount: 18900,
    featured: false,
    sellerId: SELLERS[0].id, sellerName: SELLERS[0].name, sellerPincode: SELLERS[0].pincode, sellerCity: SELLERS[0].city, sellerState: SELLERS[0].state,
    availabilityRange: "india",
    tags: ["ClassWiz", "552 Functions"],
    keyFeatures: ["Dual Solar & Battery power", "High res 192x63 dot matrix screen"],
    specs: { "Power": "Solar + LR44 Battery", "Functions": "552" },
    createdAt: new Date().toISOString()
  },

  // =========================================================================
  // 21. HEALTH CARE (6-10 Products)
  // =========================================================================
  {
    id: "omron-hem-7120-bp-monitor",
    _id: "omron-hem-7120-bp-monitor",
    name: "Omron HEM-7120 Fully Automatic Digital Blood Pressure Monitor",
    brand: "Omron",
    description: "Intellisense Technology automatically applies the right amount of pressure for fast, accurate and comfortable measurements.",
    price: 2299,
    originalPrice: 3449,
    image: ["https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&auto=format&fit=crop&q=80"],
    category: "Health Care",
    subcategory: "Blood Pressure Monitors",
    inventory: 54,
    rating: 4.7,
    reviewsCount: 108000,
    featured: false,
    sellerId: SELLERS[1].id, sellerName: SELLERS[1].name, sellerPincode: SELLERS[1].pincode, sellerCity: SELLERS[1].city, sellerState: SELLERS[1].state,
    availabilityRange: "india",
    tags: ["Clinically Validated", "Intellisense"],
    keyFeatures: ["Irregular heartbeat detection", "Cuff wrapping guide signal"],
    specs: { "Cuff Size": "22-32 cm", "Type": "Upper Arm" },
    createdAt: new Date().toISOString()
  },

  // =========================================================================
  // 22. FOOD & NUTRITION (6-10 Products)
  // =========================================================================
  {
    id: "optimum-nutrition-gold-standard-100-whey-2kg",
    _id: "optimum-nutrition-gold-standard-100-whey-2kg",
    name: "Optimum Nutrition (ON) Gold Standard 100% Whey Protein (2kg, Double Rich Chocolate)",
    brand: "Optimum Nutrition",
    description: "World's #1 selling whey protein. 24g of high quality protein per serving primarily from Whey Isolate, with 5.5g natural BCAAs.",
    price: 6899,
    originalPrice: 8099,
    image: ["https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=800&auto=format&fit=crop&q=80"],
    category: "Food & Nutrition",
    subcategory: "Protein Powder",
    inventory: 30,
    rating: 4.8,
    reviewsCount: 24500,
    featured: true,
    sellerId: SELLERS[3].id, sellerName: SELLERS[3].name, sellerPincode: SELLERS[3].pincode, sellerCity: SELLERS[3].city, sellerState: SELLERS[3].state,
    availabilityRange: "india",
    tags: ["Authentic ON", "Banned Substance Tested"],
    keyFeatures: ["24g Protein per scoop", "5.5g BCAAs & 4g Glutamine"],
    specs: { "Weight": "2 kg / 4.4 lbs", "Flavor": "Double Rich Chocolate" },
    createdAt: new Date().toISOString()
  },

  // =========================================================================
  // 23. GARDEN & OUTDOOR (6-10 Products)
  // =========================================================================
  {
    id: "kyari-indoor-money-plant-variegated-pot",
    _id: "kyari-indoor-money-plant-variegated-pot",
    name: "Kyari Live Variegated Money Plant in Self-Watering Ceramic Pot",
    brand: "Kyari",
    description: "NASA recommended air-purifying indoor plant. Includes self-watering glazed ceramic pot that keeps soil moist for up to 10 days.",
    price: 499,
    originalPrice: 799,
    image: ["https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=800&auto=format&fit=crop&q=80"],
    category: "Garden & Outdoor",
    subcategory: "Plants",
    inventory: 40,
    rating: 4.6,
    reviewsCount: 2100,
    featured: false,
    sellerId: SELLERS[0].id, sellerName: SELLERS[0].name, sellerPincode: SELLERS[0].pincode, sellerCity: SELLERS[0].city, sellerState: SELLERS[0].state,
    availabilityRange: "india",
    tags: ["Air Purifying", "Self Watering"],
    keyFeatures: ["Easy low light maintenance", "Includes organic soil mix"],
    specs: { "Height": "10-12 Inches", "Pot Material": "Ceramic" },
    createdAt: new Date().toISOString()
  },

  // =========================================================================
  // 24. INDUSTRIAL & SCIENTIFIC (6-10 Products)
  // =========================================================================
  {
    id: "bosch-gsb-180-li-cordless-drill-kit",
    _id: "bosch-gsb-180-li-cordless-drill-kit",
    name: "Bosch Professional GSB 180-LI Cordless Impact Drill Kit (18V, 2x Batteries)",
    brand: "Bosch",
    description: "Powerful 18V impact drill driver for masonry, wood and metal. Includes two 2.0Ah lithium-ion batteries, charger, and sturdy carrying case.",
    price: 8990,
    originalPrice: 11500,
    image: ["https://images.unsplash.com/photo-1504148455328-c376907d081c?w=800&auto=format&fit=crop&q=80"],
    category: "Industrial & Scientific",
    subcategory: "Industrial Tools",
    inventory: 18,
    rating: 4.8,
    reviewsCount: 410,
    featured: false,
    sellerId: SELLERS[2].id, sellerName: SELLERS[2].name, sellerPincode: SELLERS[2].pincode, sellerCity: SELLERS[2].city, sellerState: SELLERS[2].state,
    availabilityRange: "india",
    tags: ["Bosch Heavy Duty", "2x Batteries"],
    keyFeatures: ["54 Nm maximum torque", "2-speed metal gearbox"],
    specs: { "Voltage": "18V", "Battery": "2x 2.0Ah Li-Ion" },
    createdAt: new Date().toISOString()
  },

  // =========================================================================
  // 25. GIFT ITEMS (6-10 Products)
  // =========================================================================
  {
    id: "cadbury-celebrations-rich-dry-fruit-gift-pack",
    _id: "cadbury-celebrations-rich-dry-fruit-gift-pack",
    name: "Cadbury Celebrations Rich Dry Fruit Gourmet Gift Pack (264g)",
    brand: "Cadbury",
    description: "An exquisite assortment of roasted almonds, cashews and raisins coated in silky Cadbury milk chocolate inside a festive tin box.",
    price: 450,
    originalPrice: 500,
    image: ["https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=800&auto=format&fit=crop&q=80"],
    category: "Gift Items",
    subcategory: "Gift Hampers",
    inventory: 150,
    rating: 4.8,
    reviewsCount: 14200,
    featured: false,
    sellerId: SELLERS[0].id, sellerName: SELLERS[0].name, sellerPincode: SELLERS[0].pincode, sellerCity: SELLERS[0].city, sellerState: SELLERS[0].state,
    availabilityRange: "india",
    tags: ["Festive Gift", "Tin Box"],
    keyFeatures: ["Chocolate covered premium almonds & cashews"],
    specs: { "Weight": "264g", "Packaging": "Decorative Tin Box" },
    createdAt: new Date().toISOString()
  },

  // =========================================================================
  // 26. ART & CRAFT (6-10 Products)
  // =========================================================================
  {
    id: "winsor-newton-cotman-watercolor-studio-set-24",
    _id: "winsor-newton-cotman-watercolor-studio-set-24",
    name: "Winsor & Newton Cotman Water Colour Studio Set (24 Half Pans)",
    brand: "Winsor & Newton",
    description: "High quality fine art watercolor pans featuring high tinting strength, transparency, and excellent lightfastness rating.",
    price: 2899,
    originalPrice: 3500,
    image: ["https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&auto=format&fit=crop&q=80"],
    category: "Art & Craft",
    subcategory: "Drawing Supplies",
    inventory: 30,
    rating: 4.9,
    reviewsCount: 890,
    featured: false,
    sellerId: SELLERS[4].id, sellerName: SELLERS[4].name, sellerPincode: SELLERS[4].pincode, sellerCity: SELLERS[4].city, sellerState: SELLERS[4].state,
    availabilityRange: "india",
    tags: ["Artist Grade", "Made in UK"],
    keyFeatures: ["Compact mixing palette case included"],
    specs: { "Pans": "24 Half Pans", "Medium": "Watercolour" },
    createdAt: new Date().toISOString()
  },

  // =========================================================================
  // 27. RELIGIOUS & SPIRITUAL (6-10 Products)
  // =========================================================================
  {
    id: "brass-ganesha-idol-handcrafted-statue",
    _id: "brass-ganesha-idol-handcrafted-statue",
    name: "Pure Brass Handcrafted Lord Ganesha Idol for Pooja & Vastu (6.5 Inches)",
    brand: "Aura Sacred",
    description: "Heavy solid brass handcrafted Ganesha statue with intricate carving and antique golden finish. Perfect for home temple and inauguration gifts.",
    price: 1899,
    originalPrice: 2499,
    image: ["https://images.unsplash.com/photo-1606293926075-69a00dbfde81?w=800&auto=format&fit=crop&q=80"],
    category: "Religious & Spiritual",
    subcategory: "Idols",
    inventory: 40,
    rating: 4.9,
    reviewsCount: 1650,
    featured: false,
    sellerId: SELLERS[0].id, sellerName: SELLERS[0].name, sellerPincode: SELLERS[0].pincode, sellerCity: SELLERS[0].city, sellerState: SELLERS[0].state,
    availabilityRange: "india",
    tags: ["100% Solid Brass", "Handcrafted"],
    keyFeatures: ["Antique gold protective polish", "Heavy weight 1.2 kg"],
    specs: { "Height": "6.5 Inches", "Weight": "1.2 kg" },
    createdAt: new Date().toISOString()
  },

  // =========================================================================
  // 28. SOFTWARE & DIGITAL PRODUCTS (6-10 Products)
  // =========================================================================
  {
    id: "quick-heal-total-security-1-user-3-year",
    _id: "quick-heal-total-security-1-user-3-year",
    name: "Quick Heal Total Security Antivirus (1 User, 3 Years - Digital Key)",
    brand: "Quick Heal",
    description: "Comprehensive antivirus protection with Ransomware Protection, Safe Banking, Parental Control, and Webcam Protection.",
    price: 1699,
    originalPrice: 2999,
    image: ["https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&auto=format&fit=crop&q=80"],
    category: "Software & Digital Products",
    subcategory: "Antivirus",
    inventory: 500,
    rating: 4.7,
    reviewsCount: 8400,
    featured: false,
    sellerId: SELLERS[0].id, sellerName: SELLERS[0].name, sellerPincode: SELLERS[0].pincode, sellerCity: SELLERS[0].city, sellerState: SELLERS[0].state,
    availabilityRange: "india",
    tags: ["Instant Digital Email Delivery", "3-Year License"],
    keyFeatures: ["Advanced DNA scan engine", "Ransomware protection & auto backup"],
    specs: { "Validity": "3 Years", "Devices": "1 PC / Laptop" },
    createdAt: new Date().toISOString()
  },

  // =========================================================================
  // 29. E-GIFT CARDS (6-10 Products)
  // =========================================================================
  {
    id: "aura-shopping-egift-card-5000",
    _id: "aura-shopping-egift-card-5000",
    name: "Aura Premium E-Gift Card (Rs. 5000 Value)",
    brand: "Aura",
    description: "Instant electronic gift card redeemable on millions of products across all categories on Aura online store with 1 year validity.",
    price: 5000,
    originalPrice: 5000,
    image: ["https://images.unsplash.com/photo-1556742049-0a670f4a4591?w=800&auto=format&fit=crop&q=80"],
    category: "E-Gift Cards",
    subcategory: "Shopping Gift Cards",
    inventory: 999,
    rating: 5.0,
    reviewsCount: 1250,
    featured: true,
    sellerId: SELLERS[0].id, sellerName: SELLERS[0].name, sellerPincode: SELLERS[0].pincode, sellerCity: SELLERS[0].city, sellerState: SELLERS[0].state,
    availabilityRange: "india",
    tags: ["Instant Email Code", "Zero Convenience Fee"],
    keyFeatures: ["Valid for 12 months", "Can be combined with other offers"],
    specs: { "Value": "Rs. 5000", "Delivery": "Instant Email" },
    createdAt: new Date().toISOString()
  },

  // =========================================================================
  // 30. SERVICES (6-10 Products)
  // =========================================================================
  {
    id: "aura-complete-home-appliance-extended-warranty-2yr",
    _id: "aura-complete-home-appliance-extended-warranty-2yr",
    name: "Aura Protect 2-Year Extended Warranty Plan for TV & Home Appliances",
    brand: "Aura Protect",
    description: "100% cashless & hassle-free repair coverage including free doorstep pickup and drop, genuine brand spare parts, or full replacement guarantee.",
    price: 1499,
    originalPrice: 1999,
    image: ["https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&auto=format&fit=crop&q=80"],
    category: "Services",
    subcategory: "Extended Warranty",
    inventory: 999,
    rating: 4.8,
    reviewsCount: 2300,
    featured: false,
    sellerId: SELLERS[0].id, sellerName: SELLERS[0].name, sellerPincode: SELLERS[0].pincode, sellerCity: SELLERS[0].city, sellerState: SELLERS[0].state,
    availabilityRange: "india",
    tags: ["100% Cashless", "Doorstep Pickup"],
    keyFeatures: ["Covers electrical & mechanical breakdowns", "Zero deduction claims"],
    specs: { "Duration": "2 Years Extended", "Coverage": "All Major Brands" },
    createdAt: new Date().toISOString()
  }
];

// Dynamically generate extra authentic products for any subcategories needing fuller coverage
// so EVERY category has 6 to 10 rich products!
const CATEGORY_SUBS: Record<string, string[]> = {
  "Mobiles": ["Smartphones", "Feature Phones", "Refurbished Mobiles", "Mobile Accessories", "Cases & Covers", "Screen Guards", "Chargers", "Power Banks", "Cables", "Smart Watches", "Fitness Bands"],
  "Electronics": ["Laptops", "Desktop PCs", "Monitors", "Printers", "Storage Devices", "SSD", "Routers", "Tablets", "Cameras", "Headphones", "Earbuds", "Speakers", "Gaming Consoles"],
  "TV & Appliances": ["Smart TVs", "Refrigerators", "Washing Machines", "Air Conditioners", "Water Purifiers", "Microwave Ovens", "Dishwashers", "Vacuum Cleaners"],
  "Fashion": ["Men T-Shirts", "Men Shirts", "Men Jeans", "Men Jackets", "Ethnic Wear", "Sarees", "Kurtas", "Dresses", "Tops", "Women Jeans"],
  "Footwear": ["Men's Shoes", "Women's Shoes", "Kids Shoes", "Sneakers", "Sports Shoes", "Formal Shoes", "Casual Shoes", "Sandals", "Boots"],
  "Beauty & Personal Care": ["Makeup", "Skincare", "Hair Care", "Perfumes", "Grooming", "Beard Care", "Shaving Products"],
  "Home & Kitchen": ["Kitchen Tools", "Cookware", "Dinnerware", "Home Decor", "Lighting", "Bedsheets", "Wall Decor", "Clocks"],
  "Furniture": ["Sofas", "Beds", "Mattresses", "Dining Tables", "Chairs", "Office Chairs", "Study Tables", "Wardrobes", "TV Units"],
  "Grocery": ["Rice", "Atta", "Pulses", "Oil", "Ghee", "Tea", "Coffee", "Snacks", "Biscuits", "Chocolates", "Dry Fruits", "Spices"],
  "Baby Care": ["Baby Food", "Diapers", "Baby Clothing", "Baby Toys", "Baby Bath", "Strollers"],
  "Toys & Games": ["Educational Toys", "Soft Toys", "Action Figures", "Building Blocks", "Board Games", "RC Toys"],
  "Sports & Fitness": ["Gym Equipment", "Dumbbells", "Yoga Mats", "Cricket", "Football", "Badminton", "Cycling"],
  "Books & Media": ["Fiction", "Non-fiction", "Academic Books", "Comics", "Magazines", "E-books"],
  "Automotive": ["Car Accessories", "Bike Accessories", "Helmets", "Car Care", "Lubricants", "Riding Gear"],
  "Jewellery": ["Gold Jewellery", "Silver Jewellery", "Artificial Jewellery", "Necklaces", "Rings", "Earrings"],
  "Watches": ["Men's Watches", "Women's Watches", "Smart Watches", "Luxury Watches"],
  "Bags, Wallets & Luggage": ["Backpacks", "Handbags", "Wallets", "Laptop Bags", "Suitcases"],
  "Pet Supplies": ["Dog Food", "Cat Food", "Pet Grooming", "Pet Toys", "Pet Beds"],
  "Musical Instruments": ["Guitar", "Keyboard", "Drum Set", "Violin", "Microphones"],
  "Office Supplies": ["Stationery", "Calculators", "Whiteboards", "Office Furniture"],
  "Health Care": ["Vitamins", "Supplements", "Medical Devices", "Blood Pressure Monitors", "Glucometers"],
  "Food & Nutrition": ["Protein Powder", "Mass Gainers", "Energy Drinks", "Healthy Snacks", "Organic Food"],
  "Garden & Outdoor": ["Plants", "Pots", "Seeds", "Garden Tools", "Outdoor Furniture"],
  "Industrial & Scientific": ["Lab Equipment", "Safety Equipment", "Industrial Tools"],
  "Gift Items": ["Greeting Cards", "Gift Hampers", "Personalized Gifts", "Festival Gifts"],
  "Art & Craft": ["Paintings", "Drawing Supplies", "Craft Kits", "Canvas"],
  "Religious & Spiritual": ["Idols", "Incense", "Diyas", "Holy Books"],
  "Software & Digital Products": ["Antivirus", "Software Licenses", "Online Courses"],
  "E-Gift Cards": ["Shopping Gift Cards", "Gaming Gift Cards", "Brand Gift Cards"],
  "Services": ["Installation", "Extended Warranty", "Device Protection", "Repairs"]
};

// Fill out extra products so every category has 7-8 total items
Object.entries(CATEGORY_SUBS).forEach(([catName, subList], catIdx) => {
  const currentCount = REAL_PRODUCTS.filter(p => p.category === catName).length;
  const needed = 7 - currentCount;
  for (let i = 0; i < Math.max(0, needed); i++) {
    const sub = subList[i % subList.length];
    const seller = SELLERS[(catIdx + i) % SELLERS.length];
    const prodId = `${catName.toLowerCase().replace(/[^a-z0-0]+/g, '-')}-${sub.toLowerCase().replace(/[^a-z0-0]+/g, '-')}-${i+1}`;
    
    // Select domain appropriate unsplash photo
    let sampleImg = "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80";
    if (catName.includes("Mob") || catName.includes("Electr")) sampleImg = "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&auto=format&fit=crop&q=80";
    else if (catName.includes("Fash") || catName.includes("Foot")) sampleImg = "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=80";
    else if (catName.includes("Home") || catName.includes("Furn")) sampleImg = "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&auto=format&fit=crop&q=80";
    else if (catName.includes("Groc") || catName.includes("Food")) sampleImg = "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=800&auto=format&fit=crop&q=80";
    else if (catName.includes("Jewel") || catName.includes("Watch")) sampleImg = "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&auto=format&fit=crop&q=80";
    else if (catName.includes("Auto") || catName.includes("Sport")) sampleImg = "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&auto=format&fit=crop&q=80";
    
    REAL_PRODUCTS.push({
      id: prodId,
      _id: prodId,
      name: `Aura ${catName} ${sub} Edition ${i+1}`,
      brand: `Aura ${catName.split(" ")[0]}`,
      description: `Premium quality ${sub} from the ${catName} collection on Aura. Top rated product with manufacturer warranty.`,
      price: Math.floor(499 + Math.random() * 8500),
      originalPrice: Math.floor(1200 + Math.random() * 12000),
      image: [sampleImg],
      category: catName,
      subcategory: sub,
      inventory: 25 + (i * 5),
      rating: Number((4.2 + (i % 8) * 0.1).toFixed(1)),
      reviewsCount: 350 + i * 180,
      featured: i === 0,
      sellerId: seller.id, sellerName: seller.name, sellerPincode: seller.pincode, sellerCity: seller.city, sellerState: seller.state,
      availabilityRange: "india",
      tags: ["Aura Assured", "Free Delivery"],
      keyFeatures: [`Top tier ${sub} specification`, "100% Genuine Certified Quality", "Manufacturer Warranty"],
      specs: { "Category": catName, "Subcategory": sub },
      createdAt: new Date().toISOString()
    });
  }
});

async function seed() {
  console.log(`Purging old products and seeding database with ${REAL_PRODUCTS.length} clean products across all categories & subcategories...`);
  
  // 1. Write clean product catalog to data-store/products.json
  const dataDir = path.join(process.cwd(), 'data-store');
  if (!fs.existsSync(dataDir)) {
    fs.mkdirSync(dataDir, { recursive: true });
  }
  const productsJsonPath = path.join(dataDir, 'products.json');
  
  fs.writeFileSync(productsJsonPath, JSON.stringify(REAL_PRODUCTS, null, 2), 'utf-8');
  console.log(`Saved ${REAL_PRODUCTS.length} products to data-store/products.json`);

  // 2. Clear & repopulate MongoDB Atlas
  try {
    const client = new MongoClient(uri, { serverSelectionTimeoutMS: 5000 });
    await client.connect();
    console.log("Connected to MongoDB Atlas for purging & seeding...");
    const db = client.db('mern-ecommerce');
    const collection = db.collection('products');

    // Remove all previous products
    await collection.deleteMany({});
    console.log("Deleted all old products from MongoDB Atlas 'products' collection.");

    // Insert clean new products
    const result = await collection.insertMany(REAL_PRODUCTS as any[]);
    console.log(`Successfully inserted ${result.insertedCount} real products into MongoDB Atlas!`);
    await client.close();
  } catch (err: any) {
    console.warn(`MongoDB Atlas connection warning (${err.message}). Local file store updated.`);
  }
}

seed().catch(console.error);
